/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.GovernmentCoordinatorRole;
import HomePages.TableFormat;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.Message;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
//import javax.mail.*;
//import javax.mail.internet.InternetAddress;/
//import javax.mail.internet.MimeMessage;


/**
 *
 * @author Akshay
 */
public class EncourageCuredPatientsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CheckOldPatients
     */
    public EncourageCuredPatientsJPanel() {
        initComponents();
     
        tblCuredPatient.getTableHeader().setDefaultRenderer(new TableFormat());
        poppulateTable();
    }
    private void  poppulateTable(){
    
    
      DefaultTableModel dtmA = (DefaultTableModel)tblCuredPatient.getModel();
      dtmA.setRowCount(0);
      Object row[] = new Object[4];
       String line = "";  
       String splitBy = ",";  
        try   
        {  
            //parsing a CSV file into BufferedReader class constructor  
            BufferedReader br = new BufferedReader(new FileReader("CuredPatientsRecord.csv"));  
            while ((line = br.readLine()) != null)   //returns a Boolean value  
            {
            String[] csv = line.split(splitBy);    // use comma as separator 
            row[0]= csv[0];
            row[1]= csv[1];
            row[2]= csv[2];
            row[3]= csv[3];
            
            dtmA.addRow(row);
        }   }
            catch (IOException e)   
            {  e.printStackTrace(); }   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblCuredPatient = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        toTextField = new javax.swing.JTextField();
        fromTextField = new javax.swing.JTextField();
        subjectTextField = new javax.swing.JTextField();
        sendButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        messageTextField = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(208, 93, 2));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblCuredPatient.setBackground(new java.awt.Color(0, 0, 0));
        tblCuredPatient.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        tblCuredPatient.setForeground(new java.awt.Color(255, 255, 255));
        tblCuredPatient.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "UID", "Name", "Email", "Covid Cured Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCuredPatient.setGridColor(new java.awt.Color(0, 0, 0));
        tblCuredPatient.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tblCuredPatient.setRowHeight(30);
        tblCuredPatient.setShowVerticalLines(false);
        jScrollPane1.setViewportView(tblCuredPatient);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 137, 1240, 183));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("List Of Cured Patients");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 90, 268, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("To");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 400, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("From");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 460, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Subject");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 510, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Message body");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 560, -1, -1));

        toTextField.setBackground(new java.awt.Color(0, 0, 0));
        toTextField.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        toTextField.setForeground(new java.awt.Color(255, 255, 255));
        toTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toTextFieldActionPerformed(evt);
            }
        });
        add(toTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 400, 330, -1));

        fromTextField.setBackground(new java.awt.Color(0, 0, 0));
        fromTextField.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        fromTextField.setForeground(new java.awt.Color(255, 255, 255));
        fromTextField.setText("aedprojecttitans@gmail.com");
        fromTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fromTextFieldActionPerformed(evt);
            }
        });
        add(fromTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 450, 330, -1));

        subjectTextField.setBackground(new java.awt.Color(0, 0, 0));
        subjectTextField.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        subjectTextField.setForeground(new java.awt.Color(255, 255, 255));
        subjectTextField.setText("Plasma Donation Request");
        subjectTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subjectTextFieldActionPerformed(evt);
            }
        });
        add(subjectTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 500, 330, -1));

        sendButton.setBackground(new java.awt.Color(31, 31, 31));
        sendButton.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        sendButton.setForeground(new java.awt.Color(255, 255, 255));
        sendButton.setText("Send Mail");
        sendButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        sendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendButtonActionPerformed(evt);
            }
        });
        add(sendButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 500, 110, 40));

        jPanel3.setBackground(new java.awt.Color(31, 31, 31));
        jPanel3.setPreferredSize(new java.awt.Dimension(926, 70));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("Encourage Cured Patients for Plasma Donation");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, 1606, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1630, -1));

        jButton1.setBackground(new java.awt.Color(31, 31, 31));
        jButton1.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Curate Mail");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, 130, 40));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/letter.png"))); // NOI18N
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 460, 140, 130));

        messageTextField.setBackground(new java.awt.Color(0, 0, 0));
        messageTextField.setColumns(20);
        messageTextField.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        messageTextField.setForeground(new java.awt.Color(255, 255, 255));
        messageTextField.setRows(5);
        messageTextField.setText("Hi,\n\nYour valuable help is needed for a patient diagnosed of Covid-19 Corona Virus Disease.\nAs per our records you have been cured from the same and thus can help.\n\nLink to register-\nhttps://docs.google.com/forms/d/1BkQfrK2Y5xUpi9HlhO3pS7IyqBXb4hEp3eX0ZHaqE20/\nviewform?edit_requested=true#response=ACYDBNjTLt8NUEp3AEl9mr9ZwGCzuG67MeM\nHckZIeJpT_Gp5PaeE6pv_-dSDYLc7grNYUeI");
        jScrollPane2.setViewportView(messageTextField);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 600, 790, 260));
    }// </editor-fold>//GEN-END:initComponents

    private void toTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_toTextFieldActionPerformed

    private void subjectTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subjectTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subjectTextFieldActionPerformed

    private void sendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendButtonActionPerformed
        // TODO add your handling code here:
        
        if(toTextField.getText().equals("") || subjectTextField.getText().equals("")|| messageTextField.getText().equals(""))
        {
        JOptionPane.showMessageDialog(null,new JLabel(  "<html><h2><I>All fields are</I><font color='red'> mandatory</font>!</h2></html>") , "Error", JOptionPane.ERROR_MESSAGE);
            
        }
        else{
        
//       System.out.println("Preparing to send message ..");
      
       String toEmail = toTextField.getText();
//       String toEmail = "yashwant7kotipalli@gmail.com";
//       final String fromEmail = "yashwant7kotipalli@gmail.com";
       final String fromEmail = fromTextField.getText();
       final String fromEmailPassword = "teamtitans"; //your email password
       String subject = subjectTextField.getText();
        
        Properties properties = new Properties();
        properties.put("mail.smtp.starttls.enable","true");
        properties.put("mail.smtp.EnableSSL.enable","true");
        properties.put("mail.smtp.host", "smtp.gmail.com"); 
        properties.put("mail.smtp.auth","true");
        properties.put("mail.debug", "true"); 
        properties.put("mail.smtp.host","smtp.gmail.com");
        properties.setProperty("mail.smtp.socketFactory.class", "javax.net.ssl.SSLSocketFactory");   
        properties.setProperty("mail.smtp.socketFactory.fallback", "false");   
        properties.setProperty("mail.smtp.port", "465");   
        properties.setProperty("mail.smtp.socketFactory.port", "465"); 
        
        Session session = Session.getDefaultInstance(properties, new javax.mail.Authenticator() {
        protected PasswordAuthentication getPasswordAuthentication() {
            return new PasswordAuthentication(fromEmail, fromEmailPassword);
        }
       });
        
        try{
          MimeMessage message = new  MimeMessage(session);
          message.setFrom(new InternetAddress(fromEmail));
          message.addRecipient(Message.RecipientType.TO, new InternetAddress(toEmail));
          message.setSubject(subject);
          message.setText(messageTextField.getText());
          Transport.send(message);
        }
        catch(Exception ex){
            System.out.println(""+ex);
        }
        
  //      System.out.println("Sent message successfully ...");
        
     JOptionPane.showMessageDialog(null, new JLabel(  "<html><h2><I>Mail<font color='green'> sent</font> successfully!</I></h2></html>"));
        }          
       //JOptionPane.showMessageDialog(null,"Mail sent successfully!");
        
        
        
    }//GEN-LAST:event_sendButtonActionPerformed

    private void fromTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fromTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fromTextFieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
          int selectedRow = tblCuredPatient.getSelectedRow();
        if(selectedRow < 0){
            
             JOptionPane.showMessageDialog(null, new JLabel(  "<html><h2><I>Please select<font color='red'> a row</font> from the<font color='green'> table</font> to view the details!</I></h2></html>"), "Warning", JOptionPane.WARNING_MESSAGE);
           
            
            //JOptionPane.showMessageDialog(null,"Please select a row from the table first to View Details!","Warning!",JOptionPane.WARNING_MESSAGE);
        }
        else{
        
        
        toTextField.setText(String.valueOf(tblCuredPatient.getValueAt(selectedRow, 2)));        
        
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fromTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea messageTextField;
    private javax.swing.JButton sendButton;
    private javax.swing.JTextField subjectTextField;
    private javax.swing.JTable tblCuredPatient;
    private javax.swing.JTextField toTextField;
    // End of variables declaration//GEN-END:variables
}
